service: serverless-graphql

plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1
  versionFunctions: true

custom:
  serverless-offline:
    port: 4000
  webpack:
    includeModules: true

package:
  individually: true

functions:
  graphql:
    handler: src/index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get